sudo: false
language: node_js

branches:
  only:
    - master

jobs:
  include:
    - stage: release
      node_js: lts/*

      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
        - export PATH="$HOME/.yarn/bin:$PATH"

      script:
        - lerna run lint:all
        - lerna run test

      after_success:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git checkout master

      deploy:
        provider: script
        skip_cleanup: true
        keep_history: true
        script:
          - lerna publish -y
